# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_model', models.CharField(max_length=30)),
                ('number_plate', models.CharField(max_length=30)),
                ('number_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('pickup_point', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(null=True, upload_to='driversdp/')),
                ('phone_number', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Car')),
            ],
        ),
        migrations.CreateModel(
            name='Drivertag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pickup_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='tags',
            field=models.ManyToManyField(to='drivers.Drivertag'),
        ),
    ]
