# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-23 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20180523_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='destination',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Destination'),
        ),
    ]
